version: "3"

tasks:
  generate:
    aliases:
      - gen
    desc: "Generate go files"
    cmd:
      - protoc -I proto proto/sso/sso.proto --go_out=./gen/go --go_opt=paths=source_relative --go-grpc_out=./gen/go --go-grpc_opt=paths=source_relative
    env:
      PATH: $PATH:$HOME/go/bin
